version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Password123!
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - sqlserver-data:/var/opt/mssql

  api:
    image: ${DOCKER_REGISTRY-}api
    container_name: product_catalog_api
    build:
      context: .
      dockerfile: API.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=ProductCatalogDb;User Id=sa;Password=YourStrong@Password123!;TrustServerCertificate=True;
      - JWT__SecretKey=YourSuperSecretKeyThatIsAtLeast32BytesLong!
      - JWT__Issuer=ProductCatalogAPI
      - JWT__Audience=ProductCatalogClient
    depends_on:
      - sqlserver
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sqlserver-data: